---
packages_apt:
  # Desktop
  - i3
  - i3lock-fancy
  - thunar
  - arandr

  # Web & Mail
  - firefox-esr
  - thunderbird

  # Misc tools
  - galculator
  - flameshot
  - ghex
  - filezilla
  - meld
  - gitg
  - poedit
  - audacity
  - gedit
  - gscan2pdf
  - keepassxc
  - qpdf
  - gthumb
  - peek

  # Graphics
  - gimp
  - inkscape

  # Background apps
  - gammastep
  - feh

  # System tools
  - snapd
  - libsecret-tools # for `secret-tool`
  - pulseaudio-utils
  - brightnessctl
  - rclone
  - xdotool

  # Drivers etc.
  - xserver-xorg-input-wacom  # for Wacom graphics tablet

  # Runtimes etc.
  - default-jre  # Java
  - default-jdk  # Java
  - python3
  - pipx

  # Terminal tools
  - zsh
  - cookiecutter
  - direnv
  - git
  - fzf
  - tldr
  - ripgrep

  # LaTeX
  - texlive-full

  # Software engineering
  - dia  # for UML diagrams

packages_snap:
  - spotify
  - pinta
  - skype
  - telegram-desktop
  # - sqlitebrowser

vscode_extensions:
  - bbenoist.nix
  - bmewburn.vscode-intelephense-client
  - github.copilot
  - github.copilot-chat
  - ms-python.debugpy
  - ms-python.python
  - ms-python.vscode-pylance
  - rpinski.shebang-snippets
  - dhall.dhall-lang
  - dhall.vscode-dhall-lsp-server
  - ms-azuretools.vscode-docker